# Shared Secret — JWT and MongoDB credentials
apiVersion: v1
kind: Secret
metadata:
  name: medimesh-secrets
  namespace: {{ .Values.global.namespaces.backend }}
  labels:
    {{- include "medimesh.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret }}
  ADMIN_USERNAME: {{ .Values.global.secrets.adminUsername }}
  ADMIN_PASSWORD: {{ .Values.global.secrets.adminPassword }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.global.secrets.mongoRootUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.global.secrets.mongoRootPassword }}
